# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Alignment <- function(input_vec, ref_vec) {
    .Call(`_BIT_Alignment`, input_vec, ref_vec)
}

Main_Sampling <- function(N, xct, nct, tr_labels, display_progress = TRUE) {
    .Call(`_BIT_Main_Sampling`, N, xct, nct, tr_labels, display_progress)
}

