# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Name
#'
#' Description
#' @param variable Parameter_Description
#' @return Return_Description
rcpp_hello_world <- function() {
    .Call(`_BayesIMTR_rcpp_hello_world`)
}

