# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Main_Sampling <- function(N, xct, nct, tf_labels) {
    .Call(`_BayesIMTR_Main_Sampling`, N, xct, nct, tf_labels)
}

